### ISSUE TITLE
SimpleRisk host should be clearly denoted as meaning web host

### ISSUE THREAD

**Issue by kelnage** [simplerisk/installer#1]
When preparing to install the database for SimpleRisk, the page asks for the "SimpleRisk Host". However it does not make it clear that the host it refers to is the website host, and by default is populated with the database hostname. If this default is not changed during an installation that uses a remote database instance, then the installation will appear to be successful, but when you attempt to use SimpleRisk you are immediately greeted with a "Cannot connect to the database" error - as the simplerisk user will have an inappropriate entry in the Host column of the mysql.user table that means the web server cannot login to the database.

I would suggest that if the database host is not "localhost" then this should be auto-populated with the hostname of the webserver (`getenv('HTTP_HOST')` - which may be correct in some cases, but not all) or perhaps % (although obviously this is less secure) - but either way, I would definitely suggest making it more clear which host that field refers to (SimpleRisk Web Host or similar).

Alternatively, you could support an existing simplerisk database user existing at this stage of the installation, and just ask for an appropriate password - although clearly this will involve more error handling work if that user does not have the appropriate permissions to create the database/tables.

**Comment by jsokol** [comment]
I looked into this while preparing for the upcoming release.  Unfortunately, making a change like this would break way more instances than it would fix.  The majority of our users are running instances with a local database.  By changing it to the "HTTP_HOST", this would set it to a value that no longer works for local databases.  I tried with a few other values, as well, but couldn't find any configuration that works for all use cases.  The "%" option would work, but doesn't restrict access to only the SimpleRisk instance.  Like you said, it's far less secure.  I'll keep looking into this, but I couldn't figure out anything that would work for all scenarios at this point.

**Comment by kelnage** [comment]
Thanks for getting back to me @jsokol. I was only suggesting changing it to HTTP_HOST when the database was configured to be any other value than localhost - I had presumed that most people were running their databases on the same host as their webserver. At the end of the day, just clarifying the meaning of that field would probably be sufficient - and if that change doesn't work for you, perhaps just clarifying the documentation could be enough?

**Comment by jsokol** [comment]
Closing this out as we removed the separate installer and moved to using an installer embedded in the Core product.  New Core installer code does a better job of specifying the host and provides additional guidance.
