### ISSUE TITLE
Fails to correctly set MySQL user on more complex multi-server set-ups

### ISSUE THREAD

**Issue by gregharvey** [simplerisk/installer#6]
This is another issue related to (but not unique to) AWS RDS.

If the application is on one server and the database is on another, the installer currently creates a user based on `'simplerisk'@'database-server.hostname'` and sets grants accordingly too. However this is not correct, the user is connecting from an app server. So, for argument's sake, I have an app server on `172.0.0.10` and a database server on `172.0.0.20`, I specify the latter IP as the database host when I give the installer the root credentials and it assumes everything is on one box and makes a `'simplerisk'@'172.0.0.20'` user.

What it *needs* to do is ask the application server hostname/IP (in this case `172.0.0.10`) and create a user for that host, because that will be the *connecting* server hostname/IP - so the correct user to create and grant would be `'simplerisk'@'172.0.0.10'` or `'simplerisk'@'app-server.hostname'`.

Hope that makes sense!

**Comment by jsokol** [comment]
Hey Greg!  When you run the installer, it will first validate the database credentials.  At this step, there is a "Database IP/Host" value that will update the config.php file with where to talk to for the database.  This would be the IP or hostname of the Amazon RDS instance, in your case (172.0.0.20).  Once you pass the connectivity test, the next step has you enter a "SimpleRisk IP/Host" value.  This step is what creates the user and host combination for the mysql permissions.  This would be the IP or hostname of the SimpleRisk server, or 172.0.0.10, in your example.  I believe the installer should handle this scenario, but if you test and find that it does not function in this way, please do let me know and I'll look into fixing it.  Thanks!

**Comment by gregharvey** [comment]
I'll take a look, but I'm pretty sure that's what I did and it didn't work - but I'll double check if you think it should. Thanks for coming back!

**Comment by jsokol** [comment]
Sure.  Let me know how it goes.

**Comment by gregharvey** [comment]
Just to follow up, you're absolutely right of course. I didn't retest, I just checked the code, but I can see what you mean. I must've got confused somehow filling the form. Sorry for the false report.

**Comment by jsokol** [comment]
Thanks for the update, Greg!  I appreciate it.
